# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cooking Data
author: KÃªnia Sousa
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website, where I share my own views, knowledge and
  interests. I don't represent the views of my employer or clients.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:title.html
excerpt_separator: "<!-- more -->"

twitter_username: keniasousa
github_username:  keniasousa

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
